"""
Contract Generator Service

This module provides contract generation capabilities using HTML templates and
PDF conversion. Contracts are generated from collected conversational data and
rendered using Jinja2 templates with WeasyPrint for PDF generation.

The service handles:
- Loading and rendering HTML contract templates
- Data validation before PDF generation
- HTML-to-PDF conversion with CSS styling support
- Error handling for template and PDF generation issues

Contracts generated by this service are suitable for electronic signature
submission to Autentique and comply with Brazilian contract formatting standards.

Usage:
    from app.services.contract_generator import ContractGenerator

    generator = ContractGenerator()

    # Generate PDF contract from collected data
    pdf_bytes = await generator.generate_contract_pdf(
        contract_data={
            "client_name": "João Silva",
            "cpf_cnpj": "123.456.789-00",
            "service_description": "Consultoria em TI",
            "contract_value": 5000.00,
            "payment_terms": "Mensal",
            "start_date": "2026-02-01",
            "duration_months": 12,
            "special_clauses": "Renovação automática"
        },
        contract_id="CONTRACT-001"
    )

    # Save to file
    with open("contract.pdf", "wb") as f:
        f.write(pdf_bytes)

References:
    - WeasyPrint documentation: https://doc.courtbouillon.org/weasyprint/
    - Jinja2 templates: https://jinja.palletsprojects.com/
"""

from typing import Dict, Any, Optional
from datetime import datetime
import logging
import os
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, TemplateNotFound, TemplateError
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration

logger = logging.getLogger(__name__)


class ContractGeneratorError(Exception):
    """Base exception for contract generation errors."""
    pass


class ContractValidationError(ContractGeneratorError):
    """Exception raised when contract data validation fails."""
    pass


class ContractTemplateError(ContractGeneratorError):
    """Exception raised when template loading or rendering fails."""
    pass


class ContractPDFError(ContractGeneratorError):
    """Exception raised when PDF generation fails."""
    pass


class ContractGenerator:
    """
    Service for generating PDF contracts from HTML templates.

    Provides methods for validating contract data, rendering HTML templates
    with Jinja2, and converting HTML to PDF using WeasyPrint.

    The generator uses HTML templates with CSS styling located in the
    app/templates directory. The default template is 'default_contract.html'.

    Attributes:
        template_dir: Path to directory containing contract templates
        jinja_env: Jinja2 environment for template rendering
        font_config: WeasyPrint font configuration for PDF generation
    """

    # Required fields for contract generation
    REQUIRED_FIELDS = [
        "client_name",
        "cpf_cnpj",
        "service_description",
        "contract_value",
        "payment_terms",
        "start_date",
        "duration_months"
    ]

    def __init__(self, template_dir: Optional[str] = None):
        """
        Initialize contract generator with template configuration.

        Args:
            template_dir: Optional custom template directory path.
                         Defaults to app/templates relative to project root.

        Raises:
            ValueError: If template directory does not exist
        """
        # Determine template directory
        if template_dir:
            self.template_dir = Path(template_dir)
        else:
            # Default to app/templates from project root
            current_file = Path(__file__)
            app_dir = current_file.parent.parent
            self.template_dir = app_dir / "templates"

        # Validate template directory exists
        if not self.template_dir.exists():
            raise ValueError(
                f"Template directory not found: {self.template_dir}. "
                f"Please create the directory and add contract templates."
            )

        # Initialize Jinja2 environment
        self.jinja_env = Environment(
            loader=FileSystemLoader(str(self.template_dir)),
            autoescape=True,  # Auto-escape HTML for security
            trim_blocks=True,
            lstrip_blocks=True
        )

        # Configure WeasyPrint font handling
        self.font_config = FontConfiguration()

        logger.info(f"Contract generator initialized with template dir: {self.template_dir}")

    def validate_contract_data(self, data: Dict[str, Any]) -> tuple[bool, list[str]]:
        """
        Validate that all required contract fields are present and valid.

        Performs comprehensive validation of contract data including:
        - Required field presence check
        - Data type validation
        - Value range validation (positive amounts, valid dates)
        - Format validation (CPF/CNPJ basic check)

        Args:
            data: Dictionary of contract data to validate

        Returns:
            Tuple of (is_valid: bool, errors: List[str])
            - is_valid: True if all validation passes, False otherwise
            - errors: List of validation error messages (empty if valid)

        Example:
            >>> generator = ContractGenerator()
            >>> is_valid, errors = generator.validate_contract_data(data)
            >>> if not is_valid:
            ...     print("Validation errors:", errors)
        """
        errors = []

        # Check required fields presence
        for field in self.REQUIRED_FIELDS:
            if field not in data or not data[field]:
                errors.append(f"Missing required field: {field}")

        # Validate contract_value
        if "contract_value" in data:
            try:
                value = float(data["contract_value"])
                if value <= 0:
                    errors.append("contract_value must be greater than zero")
            except (ValueError, TypeError):
                errors.append("contract_value must be a valid number")

        # Validate duration_months
        if "duration_months" in data:
            try:
                duration = int(data["duration_months"])
                if duration <= 0:
                    errors.append("duration_months must be greater than zero")
            except (ValueError, TypeError):
                errors.append("duration_months must be a valid integer")

        # Validate start_date format (basic check)
        if "start_date" in data:
            try:
                # Attempt to parse as ISO date format
                datetime.fromisoformat(str(data["start_date"]))
            except (ValueError, TypeError):
                errors.append("start_date must be in YYYY-MM-DD format")

        # Validate CPF/CNPJ presence (basic check - not full validation)
        if "cpf_cnpj" in data:
            cpf_cnpj = str(data["cpf_cnpj"]).replace(".", "").replace("-", "").replace("/", "")
            if not cpf_cnpj.isdigit():
                errors.append("cpf_cnpj must contain only numbers (with optional formatting)")
            elif len(cpf_cnpj) not in [11, 14]:
                errors.append("cpf_cnpj must be 11 digits (CPF) or 14 digits (CNPJ)")

        return len(errors) == 0, errors

    async def generate_contract_pdf(
        self,
        contract_data: Dict[str, Any],
        contract_id: str,
        template_name: str = "default_contract.html"
    ) -> bytes:
        """
        Generate a PDF contract from template and contract data.

        Complete workflow:
        1. Validate contract data
        2. Load and render HTML template with Jinja2
        3. Convert HTML to PDF using WeasyPrint
        4. Return PDF as bytes

        Args:
            contract_data: Dictionary containing contract information with keys:
                - client_name: Full name of client (required)
                - cpf_cnpj: Brazilian tax ID (required)
                - service_description: Description of services (required)
                - contract_value: Contract value in BRL (required, float)
                - payment_terms: Payment terms description (required)
                - start_date: Contract start date in YYYY-MM-DD format (required)
                - duration_months: Contract duration in months (required, int)
                - special_clauses: Additional contract clauses (optional)
            contract_id: Unique identifier for this contract
            template_name: Name of HTML template file (default: "default_contract.html")

        Returns:
            PDF file content as bytes

        Raises:
            ContractValidationError: If contract data validation fails
            ContractTemplateError: If template loading or rendering fails
            ContractPDFError: If PDF generation fails

        Example:
            >>> generator = ContractGenerator()
            >>> pdf_bytes = await generator.generate_contract_pdf(
            ...     contract_data={
            ...         "client_name": "Maria Santos",
            ...         "cpf_cnpj": "987.654.321-00",
            ...         "service_description": "Desenvolvimento de software",
            ...         "contract_value": 10000.00,
            ...         "payment_terms": "3 parcelas mensais",
            ...         "start_date": "2026-03-01",
            ...         "duration_months": 6
            ...     },
            ...     contract_id="CONTRACT-2026-001"
            ... )
            >>> # Save or transmit pdf_bytes
        """
        logger.info(f"Generating contract PDF for contract_id: {contract_id}")

        # Step 1: Validate contract data
        is_valid, validation_errors = self.validate_contract_data(contract_data)
        if not is_valid:
            error_msg = f"Contract data validation failed: {', '.join(validation_errors)}"
            logger.error(error_msg)
            raise ContractValidationError(error_msg)

        # Step 2: Prepare template context
        template_context = {
            **contract_data,
            "contract_id": contract_id,
            "generation_date": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        }

        # Step 3: Render HTML template
        try:
            template = self.jinja_env.get_template(template_name)
            html_content = template.render(**template_context)
            logger.debug(f"Template '{template_name}' rendered successfully")

        except TemplateNotFound:
            error_msg = f"Template not found: {template_name} in {self.template_dir}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

        except TemplateError as e:
            error_msg = f"Template rendering error: {e}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

        except Exception as e:
            error_msg = f"Unexpected error rendering template: {e}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

        # Step 4: Convert HTML to PDF
        try:
            # Create HTML document from string
            html_doc = HTML(string=html_content, base_url=str(self.template_dir))

            # Generate PDF with font configuration
            pdf_bytes = html_doc.write_pdf(font_config=self.font_config)

            logger.info(f"PDF generated successfully for contract_id: {contract_id} ({len(pdf_bytes)} bytes)")
            return pdf_bytes

        except Exception as e:
            error_msg = f"PDF generation failed: {e}"
            logger.error(error_msg)
            raise ContractPDFError(error_msg)

    async def generate_contract_html(
        self,
        contract_data: Dict[str, Any],
        contract_id: str,
        template_name: str = "default_contract.html"
    ) -> str:
        """
        Generate HTML contract without PDF conversion.

        Useful for previewing contracts or debugging template rendering.

        Args:
            contract_data: Dictionary containing contract information
            contract_id: Unique identifier for this contract
            template_name: Name of HTML template file

        Returns:
            Rendered HTML content as string

        Raises:
            ContractValidationError: If contract data validation fails
            ContractTemplateError: If template loading or rendering fails

        Example:
            >>> generator = ContractGenerator()
            >>> html = await generator.generate_contract_html(data, "CONTRACT-001")
            >>> # Preview in browser or save to file
        """
        logger.info(f"Generating contract HTML for contract_id: {contract_id}")

        # Validate contract data
        is_valid, validation_errors = self.validate_contract_data(contract_data)
        if not is_valid:
            error_msg = f"Contract data validation failed: {', '.join(validation_errors)}"
            logger.error(error_msg)
            raise ContractValidationError(error_msg)

        # Prepare template context
        template_context = {
            **contract_data,
            "contract_id": contract_id,
            "generation_date": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        }

        # Render HTML template
        try:
            template = self.jinja_env.get_template(template_name)
            html_content = template.render(**template_context)
            logger.debug(f"HTML generated successfully for contract_id: {contract_id}")
            return html_content

        except TemplateNotFound:
            error_msg = f"Template not found: {template_name} in {self.template_dir}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

        except TemplateError as e:
            error_msg = f"Template rendering error: {e}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

        except Exception as e:
            error_msg = f"Unexpected error rendering template: {e}"
            logger.error(error_msg)
            raise ContractTemplateError(error_msg)

    def list_available_templates(self) -> list[str]:
        """
        List all available contract template files.

        Returns:
            List of template filenames (HTML files only)

        Example:
            >>> generator = ContractGenerator()
            >>> templates = generator.list_available_templates()
            >>> print("Available templates:", templates)
        """
        try:
            templates = [
                f.name for f in self.template_dir.iterdir()
                if f.is_file() and f.suffix.lower() in ['.html', '.htm']
            ]
            logger.debug(f"Found {len(templates)} template(s): {templates}")
            return sorted(templates)

        except Exception as e:
            logger.error(f"Error listing templates: {e}")
            return []
