"""
Conversation Model

Stores AI conversation state in the database for persistence across
server restarts and horizontal scaling. Replaces the previous volatile
in-memory dictionary store.

Each conversation tracks the full message history (as JSON), completion
status, and extracted structured data from the Claude AI interaction.
"""

from sqlalchemy import Column, String, Boolean, JSON, DateTime
from sqlalchemy.sql import func

from app.database import Base


class Conversation(Base):
    """
    Represents an AI-assisted conversation session for contract data collection.

    The conversation progresses through a series of questions posed by Claude AI,
    collecting client and contract information. Once complete, the extracted
    structured data is stored in the `data` JSON column.

    Attributes:
        id: UUID string serving as the primary key (generated by the API layer)
        messages: JSON array of message objects [{"role": "...", "content": "..."}]
        complete: Whether the conversation has finished collecting all data
        data: Extracted structured data from the conversation (populated on completion)
        created_at: Timestamp when conversation was started
        updated_at: Timestamp of last interaction
    """

    __tablename__ = "conversations"

    id = Column(
        String(36),
        primary_key=True,
        comment="UUID identifier for the conversation session",
    )
    messages = Column(
        JSON,
        nullable=False,
        default=list,
        comment="Array of message objects with role and content fields",
    )
    complete = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        comment="Whether conversation has finished data collection",
    )
    data = Column(
        JSON,
        nullable=True,
        comment="Extracted structured data from completed conversation",
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Conversation start timestamp",
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Last interaction timestamp",
    )

    def __repr__(self) -> str:
        return (
            f"<Conversation(id={self.id!r}, "
            f"complete={self.complete}, "
            f"messages={len(self.messages or [])} msgs)>"
        )
